### ISSUE TITLE
`Array​.prototype​.reverse` results in Maximum update depth exceeded

### ISSUE THREAD

**Issue by mjarkk** [solkimicreb/react-easy-state#81]
I need to show an array in reverse in my application, but the `.reverse` function gives a lot of errors:  
```
Warning: Cannot update during an existing state transition (such as within `render`). Render methods should be a pure function of props and state.


Uncaught Invariant Violation: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
    at invariant (http://localhost:8222/js/main.js:2032:15)
    at scheduleWork (http://localhost:8222/js/main.js:21893:5)
    at Object.enqueueSetState (http://localhost:8222/js/main.js:13146:5)
    at ReactiveClassComp../node_modules/react/cjs/react.development.js.Component.setState (http://localhost:8222/js/main.js:24520:16)
    at Function.scheduler (http://localhost:8222/js/main.js:23375:33)
    at Object.queueReaction (http://localhost:8222/js/main.js:571:14)
    at Set.forEach (<anonymous>)
    at queueReactionsForOperation (http://localhost:8222/js/main.js:564:39)
    at Object.set (http://localhost:8222/js/main.js:870:5)
    at Proxy.reverse (<anonymous>)
    at ReactiveClassComp.render (http://localhost:8222/js/main.js:29113:114)
    at ReactiveClassComp.render (http://localhost:8222/js/main.js:23381:73)
    at runAsReaction (http://localhost:8222/js/main.js:544:22)
    at ReactiveClassComp.reaction [as render] (http://localhost:8222/js/main.js:601:12)
    at finishClassComponent (http://localhost:8222/js/main.js:16718:31)
    at updateClassComponent (http://localhost:8222/js/main.js:16673:24)
    at beginWork (http://localhost:8222/js/main.js:17621:16)
    at performUnitOfWork (http://localhost:8222/js/main.js:21289:12)
    at workLoop (http://localhost:8222/js/main.js:21329:24)
    at renderRoot (http://localhost:8222/js/main.js:21412:7)
    at performWorkOnRoot (http://localhost:8222/js/main.js:22319:7)
    at performWork (http://localhost:8222/js/main.js:22231:7)
    at performSyncWork (http://localhost:8222/js/main.js:22205:3)
    at requestWork (http://localhost:8222/js/main.js:22074:5)
    at scheduleWork (http://localhost:8222/js/main.js:21888:5)
    at scheduleRootUpdate (http://localhost:8222/js/main.js:22549:3)
    at updateContainerAtExpirationTime (http://localhost:8222/js/main.js:22577:10)
    at updateContainer (http://localhost:8222/js/main.js:22634:10)
    at ReactRoot../node_modules/react-dom/cjs/react-dom.development.js.ReactRoot.render (http://localhost:8222/js/main.js:22930:3)
    at http://localhost:8222/js/main.js:23067:14
    at unbatchedUpdates (http://localhost:8222/js/main.js:22436:10)
    at legacyRenderSubtreeIntoContainer (http://localhost:8222/js/main.js:23063:5)
    at Object.render (http://localhost:8222/js/main.js:23132:12)
    at Module../src/main.js (http://localhost:8222/js/main.js:29023:50)
    at __webpack_require__ (http://localhost:8222/js/main.js:64:30)
    at http://localhost:8222/js/main.js:196:18
    at http://localhost:8222/js/main.js:199:10


The above error occurred in the <Test> component:
    in Test (created by Site)
    in Site


Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.


Uncaught Invariant Violation: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
    at invariant (http://localhost:8222/js/main.js:2032:15)
    at scheduleWork (http://localhost:8222/js/main.js:21893:5)
    at Object.enqueueSetState (http://localhost:8222/js/main.js:13146:5)
    at ReactiveClassComp../node_modules/react/cjs/react.development.js.Component.setState (http://localhost:8222/js/main.js:24520:16)
    at Function.scheduler (http://localhost:8222/js/main.js:23375:33)
    at Object.queueReaction (http://localhost:8222/js/main.js:571:14)
    at Set.forEach (<anonymous>)
    at queueReactionsForOperation (http://localhost:8222/js/main.js:564:39)
    at Object.set (http://localhost:8222/js/main.js:870:5)
    at Proxy.reverse (<anonymous>)
    at ReactiveClassComp.render (http://localhost:8222/js/main.js:29113:114)
    at ReactiveClassComp.render (http://localhost:8222/js/main.js:23381:73)
    at runAsReaction (http://localhost:8222/js/main.js:544:22)
    at ReactiveClassComp.reaction [as render] (http://localhost:8222/js/main.js:601:12)
    at finishClassComponent (http://localhost:8222/js/main.js:16718:31)
    at updateClassComponent (http://localhost:8222/js/main.js:16673:24)
    at beginWork (http://localhost:8222/js/main.js:17621:16)
    at performUnitOfWork (http://localhost:8222/js/main.js:21289:12)
    at workLoop (http://localhost:8222/js/main.js:21329:24)
    at renderRoot (http://localhost:8222/js/main.js:21412:7)
    at performWorkOnRoot (http://localhost:8222/js/main.js:22319:7)
    at performWork (http://localhost:8222/js/main.js:22231:7)
    at performSyncWork (http://localhost:8222/js/main.js:22205:3)
    at requestWork (http://localhost:8222/js/main.js:22074:5)
    at scheduleWork (http://localhost:8222/js/main.js:21888:5)
    at scheduleRootUpdate (http://localhost:8222/js/main.js:22549:3)
    at updateContainerAtExpirationTime (http://localhost:8222/js/main.js:22577:10)
    at updateContainer (http://localhost:8222/js/main.js:22634:10)
    at ReactRoot../node_modules/react-dom/cjs/react-dom.development.js.ReactRoot.render (http://localhost:8222/js/main.js:22930:3)
    at http://localhost:8222/js/main.js:23067:14
    at unbatchedUpdates (http://localhost:8222/js/main.js:22436:10)
    at legacyRenderSubtreeIntoContainer (http://localhost:8222/js/main.js:23063:5)
    at Object.render (http://localhost:8222/js/main.js:23132:12)
    at Module../src/main.js (http://localhost:8222/js/main.js:29023:50)
    at __webpack_require__ (http://localhost:8222/js/main.js:64:30)
    at http://localhost:8222/js/main.js:196:18
    at http://localhost:8222/js/main.js:199:10
```

The code i used to test this:  
```jsx
import React from 'react'
import {store, view} from 'react-easy-state'

const example = store({
  array: [1,2,3]
})

export default view(class Test extends React.Component {
  constructor() {
    super()
    this.state = {
      array: [1,2,3]
    }
  }
  render() {
    return (<div>
      <h2>Works:</h2>
      {this.state.array.reverse().map((el, i) => <div key={i}>{el}</div>)}
      
      <h2>Doesn't work:</h2>
      {example.array.reverse().map((el, i) => <div key={i}>{el}</div>)}
    </div>)
  }
})
```

**Comment by solkimicreb** [comment]
Hi!

The array.reverse method is mutating (and returning) the original array, which is generally considered a bad practice inside render methods. Is this really what you would like to do or you would like the create a new array (like the array.map method) instead?

**Comment by mjarkk** [comment]
Thanks,  

I see why that would give errors if it mutates the original array.  
Is there a good alternative way of reversing an array then?  
I have tried to write a reverse function myself but that also seems like it mutated the original array.  

But you are saying that i need to map the array first before reversing it, like this: `someArray.map(el => el).reverse()` ?

**Comment by solkimicreb** [comment]
Yep, mapping before reversing works fine. There are many ways to achieve this. The usual old-school way of doing this is `array.slice().reverse()` and the newer, somewhat nicer syntax is `[...array].reverse()` It's kind of strange that JS has no built-in method for this.

**Comment by solkimicreb** [comment]
I think this is resolved, feel free to reopen it if needed.
